import { ChangeDetectorRef, DestroyRef, ElementRef, EmbeddedViewRef, EventEmitter, TemplateRef, ViewContainerRef } from '@angular/core';
import { IToolbarMenuItem } from "./float-text-toolbar.type";
import { Overlay } from "@angular/cdk/overlay";
import * as i0 from "@angular/core";
export declare class FloatTextToolbar {
    readonly elementRef: ElementRef;
    private overlay;
    private vcr;
    readonly cdRef: ChangeDetectorRef;
    private readonly destroyRef;
    markMenu: any;
    activeMenuSet?: Set<string>;
    toolbarMenuList: Array<IToolbarMenuItem>;
    style: string;
    itemClick: EventEmitter<IToolbarMenuItem>;
    childrenTpl: TemplateRef<any>;
    markTpl: TemplateRef<any>;
    container: ViewContainerRef;
    private prevOverItem;
    embedViewRef?: EmbeddedViewRef<any>;
    constructor(elementRef: ElementRef, overlay: Overlay, vcr: ViewContainerRef, cdRef: ChangeDetectorRef, destroyRef: DestroyRef);
    onMousedown(e: MouseEvent, item: IToolbarMenuItem): void;
    onMouseEnter(e: MouseEvent, item: IToolbarMenuItem): void;
    onMark(e: MouseEvent): void;
    onMarkMouseEnter(e: MouseEvent): void;
    private _colorPickerCpr?;
    showColorPicker(target: HTMLElement): void;
    onMouseLeave(e: MouseEvent, item: IToolbarMenuItem): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<FloatTextToolbar, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<FloatTextToolbar, "bf-float-text-toolbar", never, { "markMenu": { "alias": "markMenu"; "required": false; }; "activeMenuSet": { "alias": "activeMenuSet"; "required": false; }; "toolbarMenuList": { "alias": "toolbarMenuList"; "required": false; }; "style": { "alias": "style"; "required": false; }; }, { "itemClick": "itemClick"; }, never, never, true, never>;
}
