import { ChangeDetectorRef, EmbeddedViewRef, EventEmitter, TemplateRef, ViewContainerRef } from "@angular/core";
import { IContextMenuEvent, IContextMenuItem } from "./type";
import { BaseBlock, Controller } from "../../core";
import { Overlay } from "@angular/cdk/overlay";
import * as i0 from "@angular/core";
export * from './type';
export declare class BlockFlowContextmenu {
    private cdr;
    private vcr;
    private overlay;
    private _activeBlock;
    set activeBlock(val: BaseBlock);
    get activeBlock(): BaseBlock;
    private _controller;
    set controller(val: Controller);
    get controller(): Controller;
    itemClick: EventEmitter<IContextMenuEvent>;
    destroy: EventEmitter<boolean>;
    constructor(cdr: ChangeDetectorRef, vcr: ViewContainerRef, overlay: Overlay);
    moreBlockContainer: TemplateRef<any>;
    protected baseBlockList: IContextMenuItem[];
    protected commonBlockList: IContextMenuItem[];
    protected toolList: IContextMenuItem[];
    protected hasContent: boolean;
    protected moreBlockTpr?: EmbeddedViewRef<any>;
    onClick(event: MouseEvent): void;
    onMouseDown(event: MouseEvent, item: IContextMenuItem, type: 'block' | 'tool'): void;
    onItemClicked(value: IContextMenuEvent): void;
    onShowMoreBlock(event: MouseEvent): void;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<BlockFlowContextmenu, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<BlockFlowContextmenu, "div.bf-contextmenu", never, { "activeBlock": { "alias": "activeBlock"; "required": true; }; "controller": { "alias": "controller"; "required": true; }; }, { "itemClick": "itemClick"; "destroy": "destroy"; }, never, never, true, never>;
}
