export enum ErrorCode {
  DefaultRuntimeError = 1,
  ReactiveProxyError,
  DocCollectionError,
  ModelCRUDError,
  SyncYEventError,
  SyncInputError,
  ValueNotExists,
  ValueNotInstanceOf,
  ValueNotEqual,
  MigrationError,
  SchemaValidateError,
  TransformerError,
  InlineEditorError,
  TransformerNotImplementedError,
  EdgelessExportError,
  CommandError,
  EventDispatcherError,
  SelectionError,
  MissingViewModelError,
  DatabaseBlockError,
  ParsingError,
  UserAbortError,
  ExecutionError,
  PluginError,

  // Fatal error should be greater than 10000
  DefaultFatalError = 10000,
  NoRootError,
  NoSurfaceModelError,
  NoneSupportedSSRError,
}
