import type {
  WordArtBlockProps,
} from './word-art.types'

export const WORD_ART_PRESETS = [
  {
    id: 'sunset',
    label: '落日金',
    props: {
      fillType: 'linear-gradient',
      fillColor: '#F97316',
      gradientAngle: 180,
      gradientColors: ['#FDE047', '#F97316', '#DC2626'],
      gradientStops: [0, 0.58, 1],
      outlineColor: '#9A3412',
      outlineWidthEm: 0.03,
      shadowEnabled: true,
      shadowColor: '#7C2D12',
      shadowOpacity: 0.3,
      shadowOffsetXEm: 0.08,
      shadowOffsetYEm: 0.12,
      shadowBlurEm: 0.04,
      effect: 'none',
    },
  },
  {
    id: 'ocean',
    label: '深海蓝',
    props: {
      fillType: 'linear-gradient',
      fillColor: '#2563EB',
      gradientAngle: 90,
      gradientColors: ['#67E8F9', '#4F46E5', '#C026D3'],
      gradientStops: [0, 0.55, 1],
      outlineColor: '#312E81',
      outlineWidthEm: 0.025,
      shadowEnabled: true,
      shadowColor: '#312E81',
      shadowOpacity: 0.32,
      shadowOffsetXEm: 0.04,
      shadowOffsetYEm: 0.14,
      shadowBlurEm: 0.08,
      effect: 'perspective-left',
    },
  },
  {
    id: 'mint',
    label: '薄荷青',
    props: {
      fillType: 'solid',
      fillColor: '#14B8A6',
      gradientAngle: 180,
      gradientColors: ['#5EEAD4', '#0F766E'],
      gradientStops: [0, 1],
      outlineColor: '#134E4A',
      outlineWidthEm: 0.025,
      shadowEnabled: true,
      shadowColor: '#0F766E',
      shadowOpacity: 0.24,
      shadowOffsetXEm: 0.06,
      shadowOffsetYEm: 0.1,
      shadowBlurEm: 0.08,
      effect: 'none',
    },
  },
  {
    id: 'berry',
    label: '莓果紫',
    props: {
      fillType: 'linear-gradient',
      fillColor: '#9333EA',
      gradientAngle: 135,
      gradientColors: ['#F0ABFC', '#9333EA', '#4C1D95'],
      gradientStops: [0, 0.55, 1],
      outlineColor: '#581C87',
      outlineWidthEm: 0.035,
      shadowEnabled: true,
      shadowColor: '#3B0764',
      shadowOpacity: 0.34,
      shadowOffsetXEm: 0.08,
      shadowOffsetYEm: 0.1,
      shadowBlurEm: 0.05,
      effect: 'slant-right',
    },
  },
  {
    id: 'mono',
    label: '黑白经典',
    props: {
      fillType: 'solid',
      fillColor: '#F8FAFC',
      gradientAngle: 180,
      gradientColors: ['#F8FAFC', '#CBD5E1'],
      gradientStops: [0, 1],
      outlineColor: '#0F172A',
      outlineWidthEm: 0.045,
      shadowEnabled: true,
      shadowColor: '#0F172A',
      shadowOpacity: 0.4,
      shadowOffsetXEm: 0.07,
      shadowOffsetYEm: 0.09,
      shadowBlurEm: 0,
      effect: 'none',
    },
  },
  {
    id: 'silver',
    label: '立体银',
    props: {
      fillType: 'linear-gradient',
      fillColor: '#94A3B8',
      gradientAngle: 180,
      gradientColors: ['#FFFFFF', '#CBD5E1', '#64748B', '#F8FAFC'],
      gradientStops: [0, 0.32, 0.72, 1],
      outlineColor: '#334155',
      outlineWidthEm: 0.03,
      shadowEnabled: true,
      shadowColor: '#0F172A',
      shadowOpacity: 0.3,
      shadowOffsetXEm: 0.08,
      shadowOffsetYEm: 0.1,
      shadowBlurEm: 0.04,
      effect: 'perspective-right',
    },
  },
  {
    id: 'ice',
    label: '冰晶蓝',
    props: {
      fillType: 'linear-gradient',
      fillColor: '#38BDF8',
      gradientAngle: 180,
      gradientColors: ['#ECFEFF', '#67E8F9', '#0284C7'],
      gradientStops: [0, 0.48, 1],
      outlineColor: '#075985',
      outlineWidthEm: 0.025,
      shadowEnabled: true,
      shadowColor: '#0C4A6E',
      shadowOpacity: 0.26,
      shadowOffsetXEm: 0.04,
      shadowOffsetYEm: 0.12,
      shadowBlurEm: 0.08,
      effect: 'tall',
    },
  },
  {
    id: 'forest',
    label: '森林绿',
    props: {
      fillType: 'linear-gradient',
      fillColor: '#16A34A',
      gradientAngle: 160,
      gradientColors: ['#BEF264', '#22C55E', '#166534'],
      gradientStops: [0, 0.54, 1],
      outlineColor: '#14532D',
      outlineWidthEm: 0.03,
      shadowEnabled: true,
      shadowColor: '#052E16',
      shadowOpacity: 0.28,
      shadowOffsetXEm: 0.06,
      shadowOffsetYEm: 0.1,
      shadowBlurEm: 0.05,
      effect: 'slant-up',
    },
  },
  {
    id: 'cherry',
    label: '樱桃红',
    props: {
      fillType: 'linear-gradient',
      fillColor: '#E11D48',
      gradientAngle: 180,
      gradientColors: ['#FECDD3', '#F43F5E', '#9F1239'],
      gradientStops: [0, 0.5, 1],
      outlineColor: '#881337',
      outlineWidthEm: 0.03,
      shadowEnabled: true,
      shadowColor: '#4C0519',
      shadowOpacity: 0.3,
      shadowOffsetXEm: 0.06,
      shadowOffsetYEm: 0.12,
      shadowBlurEm: 0.05,
      effect: 'wide',
    },
  },
  {
    id: 'royal',
    label: '皇家紫',
    props: {
      fillType: 'linear-gradient',
      fillColor: '#7C3AED',
      gradientAngle: 150,
      gradientColors: ['#FDE68A', '#A855F7', '#4C1D95'],
      gradientStops: [0, 0.46, 1],
      outlineColor: '#3B0764',
      outlineWidthEm: 0.035,
      shadowEnabled: true,
      shadowColor: '#2E1065',
      shadowOpacity: 0.34,
      shadowOffsetXEm: 0.08,
      shadowOffsetYEm: 0.12,
      shadowBlurEm: 0.06,
      effect: 'perspective-up',
    },
  },
  {
    id: 'neon',
    label: '霓虹粉',
    props: {
      fillType: 'solid',
      fillColor: '#F0ABFC',
      gradientAngle: 180,
      gradientColors: ['#F0ABFC', '#D946EF'],
      gradientStops: [0, 1],
      outlineColor: '#22D3EE',
      outlineWidthEm: 0.04,
      shadowEnabled: true,
      shadowColor: '#C026D3',
      shadowOpacity: 0.6,
      shadowOffsetXEm: 0,
      shadowOffsetYEm: 0,
      shadowBlurEm: 0.18,
      effect: 'none',
    },
  },
  {
    id: 'copper',
    label: '复古铜',
    props: {
      fillType: 'linear-gradient',
      fillColor: '#B45309',
      gradientAngle: 180,
      gradientColors: ['#FDE68A', '#D97706', '#78350F'],
      gradientStops: [0, 0.5, 1],
      outlineColor: '#451A03',
      outlineWidthEm: 0.035,
      shadowEnabled: true,
      shadowColor: '#451A03',
      shadowOpacity: 0.35,
      shadowOffsetXEm: 0.08,
      shadowOffsetYEm: 0.1,
      shadowBlurEm: 0.02,
      effect: 'slant-down',
    },
  },
  {
    id: 'sky-outline',
    label: '天空描边',
    props: {
      fillType: 'solid',
      fillColor: '#FFFFFF',
      gradientAngle: 180,
      gradientColors: ['#FFFFFF', '#DBEAFE'],
      gradientStops: [0, 1],
      outlineColor: '#2563EB',
      outlineWidthEm: 0.055,
      shadowEnabled: false,
      shadowColor: '#1D4ED8',
      shadowOpacity: 0.2,
      shadowOffsetXEm: 0.04,
      shadowOffsetYEm: 0.06,
      shadowBlurEm: 0.04,
      effect: 'narrow',
    },
  },
  {
    id: 'lime',
    label: '活力青柠',
    props: {
      fillType: 'linear-gradient',
      fillColor: '#84CC16',
      gradientAngle: 135,
      gradientColors: ['#FEF08A', '#A3E635', '#16A34A'],
      gradientStops: [0, 0.52, 1],
      outlineColor: '#3F6212',
      outlineWidthEm: 0.025,
      shadowEnabled: true,
      shadowColor: '#365314',
      shadowOpacity: 0.26,
      shadowOffsetXEm: 0.05,
      shadowOffsetYEm: 0.09,
      shadowBlurEm: 0.05,
      effect: 'inflate',
    },
  },
  {
    id: 'ink-blue',
    label: '墨水蓝',
    props: {
      fillType: 'solid',
      fillColor: '#1E3A8A',
      gradientAngle: 180,
      gradientColors: ['#3B82F6', '#1E3A8A'],
      gradientStops: [0, 1],
      outlineColor: '#0F172A',
      outlineWidthEm: 0.025,
      shadowEnabled: true,
      shadowColor: '#0F172A',
      shadowOpacity: 0.22,
      shadowOffsetXEm: 0.04,
      shadowOffsetYEm: 0.08,
      shadowBlurEm: 0.03,
      effect: 'short',
    },
  },
  {
    id: 'rainbow',
    label: '彩虹',
    props: {
      fillType: 'linear-gradient',
      fillColor: '#EF4444',
      gradientAngle: 90,
      gradientColors: ['#EF4444', '#FACC15', '#22C55E', '#3B82F6'],
      gradientStops: [0, 0.33, 0.66, 1],
      outlineColor: '#581C87',
      outlineWidthEm: 0.02,
      shadowEnabled: true,
      shadowColor: '#312E81',
      shadowOpacity: 0.22,
      shadowOffsetXEm: 0.04,
      shadowOffsetYEm: 0.09,
      shadowBlurEm: 0.06,
      effect: 'perspective-down',
    },
  },
] as const satisfies ReadonlyArray<{
  id: string
  label: string
  props: Partial<WordArtBlockProps>
}>

export type WordArtPresetId = typeof WORD_ART_PRESETS[number]['id']

export function getWordArtPreset(
  value: unknown,
): typeof WORD_ART_PRESETS[number] {
  return WORD_ART_PRESETS.find(item => item.id === value) ??
    WORD_ART_PRESETS[0]
}
