import type { TextBoxPresetDefinition } from "../text-box.presets";
import {
  galleryArtworkRef as artwork,
  type GalleryDecoration,
} from "./gallery-artwork";

const art = (
  id: string,
  kind: GalleryDecoration,
  accent: string,
  background?: string,
): string => artwork(id, kind, accent, background);

/** The 58 single-object styles approved in the HTML gallery prototype. */
export const GALLERY_TEXT_BOX_PRESETS = [
  {
    id: "office-simple",
    label: "基础文本框",
    cat: "office",
    defaultWidth: 390,
    defaultHeight: 178,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#FFFFFF",
      borderColor: "#7A838D",
      bw: 1,
      p: [18, 22],
      tc: "#28323D",
    },
  },
  {
    id: "office-banded",
    label: "带状引言",
    cat: "office",
    defaultWidth: 430,
    defaultHeight: 176,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#F1F5F9",
      borderColor: "#5D7894",
      bw: 1,
      bgi: art("office-banded", "banded", "#315F8C"),
      p: [24, 28],
      tc: "#263C51",
    },
  },
  {
    id: "office-facet",
    label: "切面引言",
    cat: "office",
    defaultWidth: 430,
    defaultHeight: 184,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#FFFFFF",
      borderColor: "#486A89",
      bw: 1,
      bgi: art("office-facet", "facet-right", "#397AA8"),
      p: [20, 30],
      tc: "#293D50",
    },
  },
  {
    id: "office-filigree",
    label: "花饰引言",
    cat: "office",
    defaultWidth: 430,
    defaultHeight: 190,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#FFFDF7",
      bw: 0,
      bgi: art("office-filigree", "filigree", "#9A7738"),
      p: [28, 34],
      tc: "#493E2D",
      align: "center",
      fontFamily: "Georgia, serif",
    },
  },
  {
    id: "office-shadow",
    label: "柔和阴影",
    cat: "office",
    defaultWidth: 380,
    defaultHeight: 170,
    props: {
      sh: "rounded-rectangle",
      fo: 1,
      backColor: "#FFFFFF",
      borderColor: "#D4D9DF",
      bw: 1,
      p: [20, 24],
      tc: "#27313D",
      shadow: "soft",
    },
  },
  {
    id: "office-bevel",
    label: "轻微棱台",
    cat: "office",
    defaultWidth: 370,
    defaultHeight: 164,
    props: {
      sh: "bevel",
      fo: 1,
      backColor: "#E9EEF3",
      borderColor: "#7F8D9A",
      bw: 1,
      p: [20, 24],
      tc: "#273746",
      effect: "bevel",
    },
  },
  {
    id: "office-glow",
    label: "强调发光",
    cat: "office",
    defaultWidth: 360,
    defaultHeight: 160,
    props: {
      sh: "rounded-rectangle",
      fo: 1,
      backColor: "#142C48",
      borderColor: "#65B9FF",
      bw: 1,
      p: [20, 24],
      tc: "#FFFFFF",
      shadow: "neon",
    },
  },

  {
    id: "quote-austin",
    label: "奥斯汀摘录",
    cat: "quote",
    defaultWidth: 450,
    defaultHeight: 206,
    props: {
      sh: "rectangle",
      fo: 0,
      bw: 0,
      bgi: art("quote-austin", "quote-mark", "#4F83AE"),
      p: [24, 36],
      tc: "#25384A",
      fontSize: 30,
      fontWeight: 500,
    },
  },
  {
    id: "quote-naked",
    label: "无框摘录",
    cat: "quote",
    defaultWidth: 470,
    defaultHeight: 210,
    props: {
      sh: "rectangle",
      fo: 0,
      bw: 0,
      bgi: art("quote-naked", "header-rule", "#D4523B"),
      p: [30, 32],
      tc: "#181B1F",
      fontFamily: "Georgia, serif",
      fontSize: 32,
    },
  },
  {
    id: "quote-bracket",
    label: "编辑括号",
    cat: "quote",
    defaultWidth: 420,
    defaultHeight: 190,
    props: {
      sh: "rectangle",
      fo: 0,
      bw: 0,
      bgi: art("quote-bracket", "brackets", "#75579A"),
      p: [24, 46],
      tc: "#4B3867",
      align: "center",
      fontSize: 27,
    },
  },
  {
    id: "quote-inverted",
    label: "深色陈述",
    cat: "quote",
    defaultWidth: 430,
    defaultHeight: 184,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#181D24",
      borderColor: "#181D24",
      bw: 1,
      bgi: art("quote-inverted", "split-panel", "#E7B657"),
      p: [24, 30],
      tc: "#FFFFFF",
      fontSize: 27,
    },
  },

  {
    id: "sidebar-austin",
    label: "经典侧栏",
    cat: "sidebar",
    defaultWidth: 224,
    defaultHeight: 310,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#F2F5F8",
      borderColor: "#536F89",
      bw: 1,
      bgi: art("sidebar-austin", "tabbed", "#365F82"),
      p: [34, 22],
      tc: "#2C4255",
      fontSize: 24,
    },
  },
  {
    id: "sidebar-banded",
    label: "带状侧栏",
    cat: "sidebar",
    defaultWidth: 226,
    defaultHeight: 316,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#FFF7EC",
      borderColor: "#BB712F",
      bw: 1,
      bgi: art("sidebar-banded", "banded", "#D77B2F"),
      p: [28, 22],
      tc: "#58371F",
    },
  },
  {
    id: "sidebar-facet",
    label: "切面侧栏",
    cat: "sidebar",
    defaultWidth: 230,
    defaultHeight: 320,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#EDF6F4",
      borderColor: "#2F756B",
      bw: 1,
      bgi: art("sidebar-facet", "facet-left", "#279082"),
      p: [24, 28],
      tc: "#244C46",
    },
  },
  {
    id: "sidebar-ribbon",
    label: "绶带侧栏",
    cat: "sidebar",
    defaultWidth: 232,
    defaultHeight: 300,
    props: {
      sh: "ribbon",
      fo: 1,
      backColor: "#F7F0FA",
      borderColor: "#76568B",
      bw: 1,
      p: [54, 22],
      tc: "#4D385B",
    },
  },

  {
    id: "editorial-rule",
    label: "杂志分隔",
    cat: "editorial",
    defaultWidth: 470,
    defaultHeight: 166,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#FFFFFF",
      bw: 0,
      bgi: art("editorial-rule", "bottom-rule", "#171A1E"),
      p: [18, 22],
      tc: "#191C20",
      fontSize: 29,
      fontWeight: 800,
    },
  },
  {
    id: "editorial-split",
    label: "双色版块",
    cat: "editorial",
    defaultWidth: 440,
    defaultHeight: 188,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#FFF1E8",
      borderColor: "#D26340",
      bw: 1,
      bgi: art("editorial-split", "split-panel", "#E0704D"),
      p: [22, 32],
      tc: "#553226",
      fontSize: 28,
    },
  },
  {
    id: "editorial-polaroid",
    label: "相片说明",
    cat: "editorial",
    defaultWidth: 330,
    defaultHeight: 235,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#F4F5F6",
      borderColor: "#FFFFFF",
      bw: 8,
      bgi: art("editorial-polaroid", "photo-caption", "#7A8794"),
      p: [24, 20],
      tc: "#30363D",
      fontFamily: "Arial, sans-serif",
      fontSize: 20,
      shadow: "lifted",
    },
  },
  {
    id: "editorial-ticket",
    label: "活动票券",
    cat: "editorial",
    defaultWidth: 430,
    defaultHeight: 154,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#F2ECFB",
      borderColor: "#7655A4",
      bw: 1,
      bs: "dashed",
      bgi: art("editorial-ticket", "ticket-edge", "#7655A4"),
      p: [18, 28],
      tc: "#45335F",
      fontFamily: "Arial, sans-serif",
      fontWeight: 800,
    },
  },

  {
    id: "shape-oval",
    label: "椭圆陈述",
    cat: "shape",
    defaultWidth: 330,
    defaultHeight: 225,
    props: {
      sh: "ellipse",
      fo: 1,
      backColor: "#EDF6FF",
      borderColor: "#3E79AB",
      bw: 2,
      p: [34, 46],
      tc: "#284C6B",
      align: "center",
      valign: "middle",
    },
  },
  {
    id: "shape-capsule",
    label: "胶囊标签",
    cat: "shape",
    defaultWidth: 420,
    defaultHeight: 132,
    props: {
      sh: "rounded-rectangle",
      fo: 1,
      backColor: "#173D38",
      borderColor: "#173D38",
      bw: 1,
      p: [18, 42],
      tc: "#FFFFFF",
      align: "center",
      valign: "middle",
      fontSize: 25,
    },
  },
  {
    id: "shape-hex",
    label: "六边形便笺",
    cat: "shape",
    defaultWidth: 360,
    defaultHeight: 210,
    props: {
      sh: "hexagon",
      fo: 1,
      backColor: "#FFF2D6",
      borderColor: "#B87824",
      bw: 2,
      p: [28, 46],
      tc: "#5D401D",
      align: "center",
      valign: "middle",
    },
  },
  {
    id: "shape-tag",
    label: "标签卡片",
    cat: "shape",
    defaultWidth: 390,
    defaultHeight: 168,
    props: {
      sh: "notched-right-arrow",
      fo: 1,
      backColor: "#FBEAEC",
      borderColor: "#B2485B",
      bw: 1,
      p: [20, 42],
      tc: "#692F3A",
    },
  },

  {
    id: "quote-speech",
    label: "访谈气泡",
    cat: "bubble",
    wm: ["h"],
    defaultWidth: 390,
    defaultHeight: 170,
    props: {
      sh: "rounded-speech-bubble",
      adjustments: { tailX: 150, tailY: 1000 },
      fo: 1,
      backColor: "#EEF6FF",
      borderColor: "#4A86B8",
      bw: 2,
      p: [20, 26],
      tc: "#244762",
      shadow: "soft",
    },
  },
  {
    id: "shape-cloud",
    label: "思考云朵",
    cat: "bubble",
    wm: ["h"],
    defaultWidth: 360,
    defaultHeight: 220,
    props: {
      sh: "cloud-callout",
      fo: 1,
      backColor: "#F0ECFB",
      borderColor: "#7556A3",
      bw: 2,
      p: [32, 42],
      tc: "#493762",
      align: "center",
      valign: "middle",
      shadow: "soft",
    },
  },
  {
    id: "shape-speech-right",
    label: "评论气泡",
    cat: "bubble",
    wm: ["h"],
    defaultWidth: 370,
    defaultHeight: 160,
    props: {
      sh: "wedge-round-callout",
      adjustments: { tailX: 850, tailY: 1000 },
      fo: 1,
      backColor: "#FFF5DA",
      borderColor: "#AD7A24",
      bw: 2,
      p: [18, 24],
      tc: "#5E471D",
    },
  },
  {
    id: "bubble-top-left",
    label: "左上标注",
    cat: "bubble",
    wm: ["h"],
    defaultWidth: 370,
    defaultHeight: 164,
    props: {
      sh: "wedge-round-callout",
      adjustments: { tailX: 170, tailY: 0 },
      fo: 1,
      backColor: "#EDF7F2",
      borderColor: "#43806C",
      bw: 2,
      p: [18, 24],
      tc: "#2C5548",
    },
  },
  {
    id: "bubble-top-right",
    label: "右上标注",
    cat: "bubble",
    wm: ["h"],
    defaultWidth: 370,
    defaultHeight: 164,
    props: {
      sh: "wedge-round-callout",
      adjustments: { tailX: 830, tailY: 0 },
      fo: 1,
      backColor: "#FFF0F3",
      borderColor: "#A64F65",
      bw: 2,
      p: [18, 24],
      tc: "#663444",
    },
  },
  {
    id: "bubble-bottom-center",
    label: "居中标注",
    cat: "bubble",
    wm: ["h"],
    defaultWidth: 390,
    defaultHeight: 166,
    props: {
      sh: "wedge-round-callout",
      adjustments: { tailX: 500, tailY: 1000 },
      fo: 1,
      backColor: "#F1EFFB",
      borderColor: "#7059A0",
      bw: 2,
      p: [18, 26],
      tc: "#48396A",
      align: "center",
      shadow: "soft",
    },
  },
  {
    id: "bubble-side-left",
    label: "左侧标注",
    cat: "bubble",
    wm: ["h"],
    defaultWidth: 390,
    defaultHeight: 158,
    props: {
      sh: "wedge-rect-callout",
      adjustments: { tailX: 0, tailY: 500 },
      fo: 1,
      backColor: "#EEF7FB",
      borderColor: "#367C9E",
      bw: 2,
      p: [18, 28],
      tc: "#28556B",
    },
  },
  {
    id: "bubble-side-right",
    label: "右侧标注",
    cat: "bubble",
    wm: ["h"],
    defaultWidth: 390,
    defaultHeight: 158,
    props: {
      sh: "wedge-round-callout",
      adjustments: { tailX: 1000, tailY: 500 },
      fo: 1,
      backColor: "#FFF7E8",
      borderColor: "#B07829",
      bw: 2,
      p: [18, 28],
      tc: "#65491E",
    },
  },
  {
    id: "bubble-sharp",
    label: "锐角对话",
    cat: "bubble",
    wm: ["h"],
    defaultWidth: 390,
    defaultHeight: 166,
    props: {
      sh: "wedge-rect-callout",
      adjustments: { tailX: 880, tailY: 1000 },
      fo: 1,
      backColor: "#F5F5F5",
      borderColor: "#20252B",
      bw: 2,
      p: [18, 24],
      tc: "#242A30",
      fontFamily: "Arial, sans-serif",
      fontWeight: 800,
    },
  },
  {
    id: "bubble-thought",
    label: "思考气泡",
    cat: "bubble",
    wm: ["h"],
    defaultWidth: 370,
    defaultHeight: 210,
    props: {
      sh: "cloud-callout",
      fo: 1,
      backColor: "#FFFFFF",
      borderColor: "#66717C",
      bw: 2,
      p: [30, 42],
      tc: "#36404A",
      align: "center",
      valign: "middle",
      shadow: "soft",
    },
  },
  {
    id: "bubble-comic",
    label: "漫画爆炸框",
    cat: "bubble",
    wm: ["h"],
    defaultWidth: 400,
    defaultHeight: 220,
    props: {
      sh: "explosion",
      fo: 1,
      backColor: "#FFF04F",
      borderColor: "#171717",
      bw: 3,
      p: [34, 48],
      tc: "#171717",
      align: "center",
      valign: "middle",
      fontFamily: "Arial, sans-serif",
      fontSize: 30,
      fontWeight: 900,
      shadow: "hard-offset",
    },
  },
  {
    id: "bubble-line-left",
    label: "左引线标注",
    cat: "bubble",
    wm: ["h"],
    defaultWidth: 340,
    defaultHeight: 150,
    props: {
      sh: "rectangle",
      fo: 0,
      backColor: "#FFFFFF",
      borderColor: "#52677B",
      bw: 0,
      bgi: art(
        "bubble-line-left",
        "line-callout-left",
        "#52677B",
        "#FFFFFF",
      ),
      p: [16, 22],
      tc: "#314253",
    },
  },
  {
    id: "bubble-line-right",
    label: "右引线标注",
    cat: "bubble",
    wm: ["h"],
    defaultWidth: 340,
    defaultHeight: 150,
    props: {
      sh: "rectangle",
      fo: 0,
      backColor: "#F8F0FA",
      borderColor: "#81588B",
      bw: 0,
      bgi: art(
        "bubble-line-right",
        "line-callout-right",
        "#81588B",
        "#F8F0FA",
      ),
      p: [16, 22],
      tc: "#563A5E",
    },
  },
  {
    id: "bubble-whisper",
    label: "低语气泡",
    cat: "bubble",
    wm: ["h"],
    defaultWidth: 370,
    defaultHeight: 160,
    props: {
      sh: "rounded-speech-bubble",
      adjustments: { tailX: 180, tailY: 1000 },
      fo: 1,
      backColor: "#F9FBFD",
      borderColor: "#7B8794",
      bw: 2,
      bs: "dashed",
      p: [18, 24],
      tc: "#4C5762",
    },
  },

  {
    id: "note-folded",
    label: "折角便笺",
    cat: "note",
    defaultWidth: 340,
    defaultHeight: 220,
    props: {
      sh: "folded-corner",
      fo: 1,
      backColor: "#FFF8C9",
      borderColor: "#BEA548",
      bw: 1,
      bgi: art("note-folded", "folded-corner", "#D3B64D"),
      p: [28, 26],
      tc: "#5A4C23",
      shadow: "soft",
    },
  },
  {
    id: "note-torn",
    label: "撕边纸张",
    cat: "note",
    defaultWidth: 410,
    defaultHeight: 190,
    props: {
      sh: "wave",
      fo: 1,
      backColor: "#FFFDF4",
      borderColor: "#B6A57E",
      bw: 1,
      p: [26, 30],
      tc: "#4C4536",
      fontFamily: "Georgia, serif",
      shadow: "soft",
    },
  },
  {
    id: "note-notebook",
    label: "活页纸",
    cat: "note",
    defaultWidth: 350,
    defaultHeight: 230,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#FFFEF7",
      borderColor: "#7E9EB9",
      bw: 1,
      bgi: art("note-notebook", "notebook-lines", "#5E91B7"),
      p: [26, 30],
      tc: "#334B5D",
      shadow: "soft",
    },
  },
  {
    id: "note-scroll",
    label: "经典卷轴",
    cat: "note",
    defaultWidth: 400,
    defaultHeight: 205,
    props: {
      sh: "rounded-rectangle",
      fo: 1,
      backColor: "#F7EDD6",
      borderColor: "#8C7045",
      bw: 1,
      bgi: art("note-scroll", "scroll", "#A88A5A"),
      p: [30, 34],
      tc: "#4E3D27",
      align: "center",
      fontFamily: "Georgia, serif",
      shadow: "soft",
    },
  },

  {
    id: "culture-lattice",
    label: "中式窗棂",
    cat: "culture",
    defaultWidth: 420,
    defaultHeight: 210,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#FFFAF2",
      borderColor: "#8A352D",
      bw: 2,
      bgi: art("culture-lattice", "lattice-frame", "#A13E34"),
      p: [34, 42],
      tc: "#542D28",
      align: "center",
      fontFamily: "Songti SC, serif",
    },
  },
  {
    id: "culture-seal",
    label: "朱印笺",
    cat: "culture",
    defaultWidth: 360,
    defaultHeight: 218,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#FFFAF5",
      borderColor: "#AF3E32",
      bw: 2,
      bgi: art("culture-seal", "seal-frame", "#B43A30"),
      p: [30, 38],
      tc: "#572A25",
      align: "center",
      fontFamily: "Songti SC, serif",
    },
  },
  {
    id: "culture-washi",
    label: "和纸留白",
    cat: "culture",
    defaultWidth: 410,
    defaultHeight: 190,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#F5F0E5",
      borderColor: "#8B806E",
      bw: 1,
      bgi: art("culture-washi", "washi-grain", "#9D8D75"),
      p: [26, 32],
      tc: "#49443B",
      fontFamily: "Yu Mincho, Songti SC, serif",
      shadow: "soft",
    },
  },
  {
    id: "culture-deco",
    label: "装饰艺术",
    cat: "culture",
    defaultWidth: 430,
    defaultHeight: 210,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#111820",
      borderColor: "#D7B65A",
      bw: 2,
      bgi: art("culture-deco", "art-deco", "#D7B65A"),
      p: [32, 42],
      tc: "#FFF7DB",
      align: "center",
      fontFamily: "Arial, sans-serif",
      fontSize: 29,
      shadow: "lifted",
    },
  },
  {
    id: "culture-bauhaus",
    label: "包豪斯海报",
    cat: "culture",
    defaultWidth: 420,
    defaultHeight: 205,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#F3EAD9",
      borderColor: "#232323",
      bw: 3,
      bgi: art("culture-bauhaus", "bauhaus", "#D73A2E"),
      p: [26, 34],
      tc: "#222222",
      fontFamily: "Arial, sans-serif",
      fontSize: 30,
      fontWeight: 900,
    },
  },
  {
    id: "culture-nouveau",
    label: "新艺术边框",
    cat: "culture",
    defaultWidth: 390,
    defaultHeight: 230,
    props: {
      sh: "rounded-rectangle",
      fo: 1,
      backColor: "#EEF2E7",
      borderColor: "#54705A",
      bw: 2,
      bgi: art("culture-nouveau", "nouveau-frame", "#718C70"),
      p: [38, 42],
      tc: "#344A39",
      align: "center",
      fontFamily: "Georgia, serif",
    },
  },
  {
    id: "culture-brutalist",
    label: "粗野主义色块",
    cat: "culture",
    defaultWidth: 390,
    defaultHeight: 176,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#FFF44D",
      borderColor: "#151515",
      bw: 4,
      p: [18, 24],
      tc: "#111111",
      fontFamily: "Arial, sans-serif",
      fontSize: 29,
      fontWeight: 900,
      shadow: "hard-offset",
    },
  },

  {
    id: "material-glass",
    label: "磨砂玻璃",
    cat: "material",
    defaultWidth: 400,
    defaultHeight: 190,
    props: {
      sh: "rounded-rectangle",
      fo: 0.66,
      backColor: "#ECF7FF",
      borderColor: "#FFFFFF",
      bw: 1,
      p: [24, 28],
      tc: "#244158",
      shadow: "soft",
    },
  },
  {
    id: "material-blueprint",
    label: "蓝图网格",
    cat: "material",
    defaultWidth: 430,
    defaultHeight: 202,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#174C78",
      borderColor: "#94C9EF",
      bw: 1,
      bgi: art("material-blueprint", "blueprint-grid", "#9BD3F8"),
      p: [24, 30],
      tc: "#FFFFFF",
      fontFamily: "Arial, sans-serif",
    },
  },
  {
    id: "material-chalk",
    label: "黑板质感",
    cat: "material",
    defaultWidth: 420,
    defaultHeight: 210,
    props: {
      sh: "rectangle",
      fo: 1,
      backColor: "#183B34",
      borderColor: "#B9A16C",
      bw: 6,
      bgi: art("material-chalk", "chalk-grain", "#F0DFAD"),
      p: [28, 32],
      tc: "#F5F0DF",
      fontFamily: "Comic Sans MS, cursive",
      shadow: "soft",
    },
  },
  {
    id: "material-metal",
    label: "拉丝金属",
    cat: "material",
    defaultWidth: 400,
    defaultHeight: 172,
    props: {
      sh: "rounded-rectangle",
      fo: 1,
      backColor: "#E7EAEC",
      borderColor: "#69747D",
      bw: 2,
      bgi: art("material-metal", "brushed-metal", "#69747D"),
      p: [20, 28],
      tc: "#263039",
      fontFamily: "Arial, sans-serif",
      fontWeight: 800,
      shadow: "soft",
    },
  },
  {
    id: "material-neon",
    label: "霓虹灯牌",
    cat: "material",
    defaultWidth: 390,
    defaultHeight: 170,
    props: {
      sh: "rounded-rectangle",
      fo: 1,
      backColor: "#101126",
      borderColor: "#54E8FF",
      bw: 2,
      p: [22, 28],
      tc: "#F1FDFF",
      align: "center",
      fontFamily: "Arial, sans-serif",
      fontSize: 28,
      shadow: "neon",
    },
  },
  {
    id: "material-kraft",
    label: "牛皮纸标签",
    cat: "material",
    defaultWidth: 390,
    defaultHeight: 182,
    props: {
      sh: "rounded-rectangle",
      fo: 1,
      backColor: "#CAA873",
      borderColor: "#6F5130",
      bw: 2,
      bs: "dashed",
      bgi: art("material-kraft", "kraft-grain", "#6F5130"),
      p: [22, 28],
      tc: "#3F2D1B",
      fontFamily: "Georgia, serif",
      shadow: "soft",
    },
  },
  {
    id: "material-iridescent",
    label: "虹彩卡片",
    cat: "material",
    defaultWidth: 400,
    defaultHeight: 185,
    props: {
      sh: "rounded-rectangle",
      fo: 1,
      borderColor: "#7060A0",
      bw: 1,
      effect: "gradient-mesh",
      p: [24, 30],
      tc: "#3B3450",
      shadow: "soft",
    },
  },

  {
    id: "vertical-seal",
    label: "朱印题签",
    cat: "vertical",
    wm: ["v"],
    defaultWidth: 178,
    defaultHeight: 390,
    props: {
      sh: "rectangle",
      wm: "v",
      fo: 1,
      backColor: "#FFF9F4",
      borderColor: "#A33B2F",
      bw: 2,
      bgi: art("vertical-seal", "corner-accent", "#B84436"),
      p: [22, 18],
      tc: "#5C2C25",
      fontFamily: "Songti SC, serif",
    },
  },
  {
    id: "vertical-scroll",
    label: "卷轴竖题",
    cat: "vertical",
    wm: ["v"],
    defaultWidth: 190,
    defaultHeight: 400,
    props: {
      sh: "rounded-rectangle",
      wm: "v",
      fo: 1,
      backColor: "#F6ECD4",
      borderColor: "#80643C",
      bw: 1,
      bgi: art("vertical-scroll", "scroll", "#9D7B4A"),
      p: [24, 20],
      tc: "#4A3924",
      fontFamily: "Songti SC, serif",
      shadow: "soft",
    },
  },
  {
    id: "vertical-capsule",
    label: "现代竖签",
    cat: "vertical",
    wm: ["v"],
    defaultWidth: 150,
    defaultHeight: 390,
    props: {
      sh: "rounded-rectangle",
      wm: "v",
      fo: 1,
      backColor: "#1D4E66",
      borderColor: "#1D4E66",
      bw: 1,
      p: [30, 18],
      tc: "#FFFFFF",
      align: "center",
      valign: "middle",
      shadow: "soft",
    },
  },
] as const satisfies readonly TextBoxPresetDefinition[];
