import { ElementRef } from "@angular/core";
import { EditableBlock } from "../../core";
import { ICodeBlockModel } from "./type";
import { Overlay } from "@angular/cdk/overlay";
import 'prismjs/components/prism-javascript';
import 'prismjs/components/prism-typescript';
import 'prismjs/components/prism-css';
import 'prismjs/components/prism-markup';
import 'prismjs/components/prism-php';
import 'prismjs/components/prism-python';
import 'prismjs/components/prism-sql';
import 'prismjs/components/prism-java';
import 'prismjs/components/prism-go';
import 'prismjs/components/prism-c';
import 'prismjs/components/prism-cpp';
import 'prismjs/components/prism-csharp';
import 'prismjs/components/prism-rust';
import 'prismjs/components/prism-json';
import 'prismjs/components/prism-bash';
import 'prismjs/components/prism-git';
import 'prismjs/components/prism-kotlin';
import 'prismjs/components/prism-ruby';
import 'prismjs/components/prism-swift';
import 'prismjs/components/prism-scala';
import 'prismjs/components/prism-dart';
import 'prismjs/components/prism-mongodb';
import 'prismjs/components/prism-nginx';
import 'prismjs/components/prism-markdown';
import { _Token } from "./code-differ";
import * as i0 from "@angular/core";
export declare class CodeBlock extends EditableBlock<ICodeBlockModel> {
    private overlay;
    highlighter: ElementRef<HTMLDivElement>;
    protected lines: string[];
    private resizeSub?;
    constructor(overlay: Overlay);
    ngAfterViewInit(): void;
    protected oldTokens: _Token[];
    highlight: (text?: string) => void;
    onKeydown(e: KeyboardEvent): void;
    setLines(): void;
    changeLanguage(mode: string): void;
    showLangList(e: Event): void;
    onCopyText(e: Event): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<CodeBlock, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CodeBlock, "div.code-block", never, {}, {}, never, never, true, never>;
}
