import {BUNDLED_EDITOR_SCHEMAS} from '../editor/bundled-capabilities'
import {BLOCKCRAFT_BUILTIN_BLOCK_AGENT_CAPABILITIES} from './builtin-agent-capabilities'

describe('built-in Block Agent capabilities', () => {
  it('keeps capability ids and flavours unique', () => {
    const ids = BLOCKCRAFT_BUILTIN_BLOCK_AGENT_CAPABILITIES.map(item => item.id)
    const flavours = BLOCKCRAFT_BUILTIN_BLOCK_AGENT_CAPABILITIES.map(
      item => item.flavour,
    )

    expect(new Set(ids).size).toBe(ids.length)
    expect(new Set(flavours).size).toBe(flavours.length)
  })

  it('targets an installed Schema with the same version', () => {
    const schemaVersions = new Map<string, number>(
      BUNDLED_EDITOR_SCHEMAS.map(schema => [
        schema.flavour,
        schema.metadata.version,
      ]),
    )

    for (const capability of BLOCKCRAFT_BUILTIN_BLOCK_AGENT_CAPABILITIES) {
      const schemaVersion = schemaVersions.get(capability.flavour)
      expect(schemaVersion)
        .withContext(`missing Schema for Agent capability ${capability.flavour}`)
        .toBeDefined()
      expect(capability.schemaVersion)
        .withContext(`stale Agent capability ${capability.flavour}`)
        .toBe(schemaVersion)
    }
  })

  it('does not grant direct creation to structural leaf Schemas', () => {
    const capabilities = new Map(
      BLOCKCRAFT_BUILTIN_BLOCK_AGENT_CAPABILITIES.map(item => [
        item.flavour,
        item,
      ]),
    )

    for (const flavour of [
      'table-row',
      'table-cell',
      'column',
      'shape-text',
      'mermaid-textarea',
    ]) {
      expect(capabilities.get(flavour)?.createParameters)
        .withContext(`${flavour} must be generated by its owning Block`)
        .toBeUndefined()
    }
  })
})
