import { Config } from "./config";
export declare class BlockSelection {
    config: Config;
    private host;
    private document;
    private baseHostRect;
    private mouseStartPos;
    private mousePos;
    private triggerElement;
    private store;
    private selectionAreaEle;
    private onSelectingSub;
    private selectableElements;
    get storeSize(): number;
    get selectedElements(): Set<Element>;
    private readonly eventListeners;
    private isSelecting;
    constructor(config: Config);
    clear(): void;
    selectElement(element: Element): void;
    unselectElement(element: Element): void;
    on(event: 'start' | 'move' | 'end', callback: (elements: Set<Element>) => void): void;
    private bindEvents;
    onMousedown: (event: MouseEvent) => void;
    onContentEditableMouseMove: (event: MouseEvent) => void;
    onMousemove: (event: MouseEvent) => void;
    private startSelecting;
    onMouseMovePicking: (event: MouseEvent) => void;
    onMouseup: (event: MouseEvent) => void;
    private lastCalculateIndex;
    calculateSelectionAreaContain(): void;
    endSelect(): void;
    createSelectionArea(): void;
    repaintSelectionArea(): void;
    removeSelectionArea(): void;
}
