// 兼容公共入口；领域实现与默认装配分离。
export {BlockCraftDoc} from '../../editor/document'
export {Y_BLOCK_MAP_NAME, type DocConfig} from './document'
export * from './crud'
export * from './vm'
export * from './block-position'
export * from './model-graph'
export * from './block-readonly.types'
export * from './block-readonly-manager'
export * from './block-mutation-policy'
export * from './undoManger'
export * from './structure-transform'
